import type {
  ContractVersionRecord,
  DestinationConfig,
  RetryPolicy,
} from "@/src/domain/contracts/contract";

const DEFAULT_RETRY: RetryPolicy = {
  maxAttempts: 3,
  backoffMs: [1000, 5000, 15000],
  deadLetterAfterMax: true,
};

export const SEED_DESTINATIONS: DestinationConfig[] = [
  {
    id: "22222222-2222-4222-8222-222222222001",
    code: "MOCK_PAYER",
    name: "Mock Payer Endpoint",
    adapterKey: "mock",
    endpoint: "mock://payer/noa",
    authType: "NONE",
    active: true,
  },
  {
    id: "22222222-2222-4222-8222-222222222002",
    code: "SF_NOA_INBOX",
    name: "Salesforce NOA Inbox (mock)",
    adapterKey: "salesforce",
    endpoint: "mock://salesforce/noa",
    authType: "OAUTH2",
    authConfig: { clientIdEnv: "SALESFORCE_CLIENT_ID" },
    active: true,
  },
  {
    id: "22222222-2222-4222-8222-222222222003",
    code: "PEGA_NOA_CASE",
    name: "Pega NOA Case (mock)",
    adapterKey: "pega",
    endpoint: "mock://pega/noa",
    authType: "API_KEY",
    authConfig: { apiKeyEnv: "PEGA_API_KEY" },
    active: true,
  },
];

export const SEED_CONTRACTS: ContractVersionRecord[] = [
  {
    id: "44444444-4444-4444-8444-444444444001",
    contractBusinessId: "MEDICARE_NOA_MOCK_V1",
    name: "Medicare NOA → Mock Payer",
    version: 1,
    payer: "MEDICARE",
    product: "NOA",
    payloadFormat: "JSON",
    transport: "REST",
    destinationId: "22222222-2222-4222-8222-222222222001",
    transformerCode: "MEDICARE_NOA_MOCK_TRANSFORM",
    acknowledgementType: "HTTP_200_BODY",
    retryPolicy: DEFAULT_RETRY,
    requiredFields: [
      "notificationType",
      "admissionDateTime",
      "patient.lastName",
      "correlationId",
    ],
    effectiveDate: "2020-01-01T00:00:00.000Z",
    expirationDate: null,
    active: true,
  },
  {
    id: "44444444-4444-4444-8444-444444444002",
    contractBusinessId: "MEDICARE_NOA_SF_V1",
    name: "Medicare NOA → Salesforce",
    version: 1,
    payer: "MEDICARE",
    product: "NOA",
    payloadFormat: "JSON",
    transport: "REST",
    destinationId: "22222222-2222-4222-8222-222222222002",
    transformerCode: "MEDICARE_NOA_SF_TRANSFORM",
    acknowledgementType: "HTTP_200_BODY",
    retryPolicy: DEFAULT_RETRY,
    requiredFields: [
      "notificationType",
      "admissionDateTime",
      "PatientLastName",
      "correlationId",
    ],
    effectiveDate: "2020-01-01T00:00:00.000Z",
    expirationDate: null,
    active: true,
  },
  {
    id: "44444444-4444-4444-8444-444444444003",
    contractBusinessId: "MEDICARE_NOA_PEGA_V1",
    name: "Medicare NOA → Pega",
    version: 1,
    payer: "MEDICARE",
    product: "NOA",
    payloadFormat: "JSON",
    transport: "REST",
    destinationId: "22222222-2222-4222-8222-222222222003",
    transformerCode: "MEDICARE_NOA_PEGA_TRANSFORM",
    acknowledgementType: "HTTP_200_BODY",
    retryPolicy: DEFAULT_RETRY,
    requiredFields: [
      "notificationType",
      "AdmissionDateTime",
      "MemberLastName",
      "correlationId",
    ],
    effectiveDate: "2020-01-01T00:00:00.000Z",
    expirationDate: null,
    active: true,
  },
  {
    id: "44444444-4444-4444-8444-444444444004",
    contractBusinessId: "COMMERCIAL_NOA_MOCK_V1",
    name: "Commercial NOA → Mock Payer (generic payer-type fallback)",
    version: 1,
    payer: "COMMERCIAL",
    product: "NOA",
    payloadFormat: "JSON",
    transport: "REST",
    destinationId: "22222222-2222-4222-8222-222222222001",
    transformerCode: "MEDICARE_NOA_MOCK_TRANSFORM",
    acknowledgementType: "HTTP_200_BODY",
    retryPolicy: DEFAULT_RETRY,
    requiredFields: [
      "notificationType",
      "admissionDateTime",
      "patient.lastName",
      "correlationId",
    ],
    effectiveDate: "2020-01-01T00:00:00.000Z",
    expirationDate: null,
    active: true,
    profile: {
      sourceType: "GENERIC_PAYER_TYPE",
      transactionType: "ADMISSION_NOTIFICATION",
      notificationRequirement: "REQUIRED",
      authorizationRequirement: "UNKNOWN",
      notificationWindow: "UNKNOWN",
      acknowledgementBehavior: "MOCK_HTTP_ACK_NOT_AUTHORIZATION",
      transformKind: "DEMO_TRANSFORM",
    },
  },
  {
    id: "44444444-4444-4444-8444-444444444005",
    contractBusinessId: "MEDICAID_NOA_MOCK_V1",
    name: "Medicaid NOA → Mock Payer",
    version: 1,
    payer: "MEDICAID",
    product: "NOA",
    payloadFormat: "JSON",
    transport: "REST",
    destinationId: "22222222-2222-4222-8222-222222222001",
    transformerCode: "MEDICARE_NOA_MOCK_TRANSFORM",
    acknowledgementType: "HTTP_200_BODY",
    retryPolicy: DEFAULT_RETRY,
    requiredFields: [
      "notificationType",
      "admissionDateTime",
      "patient.lastName",
      "correlationId",
    ],
    effectiveDate: "2020-01-01T00:00:00.000Z",
    expirationDate: null,
    active: true,
    profile: {
      sourceType: "GENERIC_PAYER_TYPE",
      transactionType: "ADMISSION_NOTIFICATION",
      acknowledgementBehavior: "MOCK_HTTP_ACK_NOT_AUTHORIZATION",
      transformKind: "DEMO_TRANSFORM",
    },
  },
  {
    id: "44444444-4444-4444-8444-444444444006",
    contractBusinessId: "AETNA_COMMERCIAL_INPATIENT_NOTIFICATION_V1",
    name: "Aetna Commercial inpatient admission notification profile",
    version: 1,
    payer: "COMMERCIAL",
    product: "NOA",
    payerBrand: "Aetna",
    planProduct: "Commercial",
    payloadFormat: "JSON",
    transport: "REST",
    destinationId: "22222222-2222-4222-8222-222222222001",
    transformerCode: "AETNA_ADMISSION_NOTIFICATION_V1",
    acknowledgementType: "HTTP_200_BODY",
    retryPolicy: DEFAULT_RETRY,
    requiredFields: [
      "transactionKind",
      "transformKind",
      "memberId",
      "dateOfBirth",
      "admissionDateTime",
      "diagnosisCode",
      "facilityNpi",
      "correlationId",
    ],
    effectiveDate: "2020-01-01T00:00:00.000Z",
    expirationDate: null,
    active: true,
    profile: {
      sourceType: "PUBLISHED_PAYER_REQUIREMENT_PROFILE",
      payerBrand: "Aetna",
      planProduct: "Commercial",
      transactionType: "ADMISSION_NOTIFICATION",
      notificationRequirement: "REQUIRED",
      authorizationRequirement: "NOT_REQUIRED_FOR_EMERGENCY_SERVICES",
      notificationWindow: {
        value: 2,
        unit: "BUSINESS_DAYS",
        startEvent: "EMERGENCY_ADMISSION_TIME",
      },
      submissionChannels: ["UNKNOWN"],
      acknowledgementBehavior:
        "MOCK_DELIVERY_ACK_ONLY — not an authorization approval",
      transformKind: "SYNTHETIC_DEMO_TRANSFORM",
      sourceReference: {
        requirementIds: [
          "AETNA-COMM-INPATIENT-NOTIFICATION-001",
          "AETNA-COMM-REQUIRED-INFO-001",
        ],
        source: "Aetna Participating Provider Precertification List (2026)",
        sourceUrl:
          "https://www.aetna.com/content/dam/aetna/pdfs/aetnacom/healthcare-professionals/2026_Precert_List.pdf",
        verificationDate: "2026-09-10",
        evidence:
          "Emergency→IP reporting within two business days; required info from precert/referral guide. Production payload schema UNKNOWN.",
      },
    },
  },
  {
    id: "44444444-4444-4444-8444-444444444007",
    contractBusinessId: "CIGNA_COMMERCIAL_INPATIENT_NOTIFICATION_V1",
    name: "Cigna Commercial inpatient admission notification profile",
    version: 1,
    payer: "COMMERCIAL",
    product: "NOA",
    payerBrand: "Cigna",
    planProduct: "Commercial",
    payloadFormat: "JSON",
    transport: "PHONE_OR_PORTAL",
    destinationId: "22222222-2222-4222-8222-222222222001",
    transformerCode: "CIGNA_ADMISSION_NOTIFICATION_V1",
    acknowledgementType: "HTTP_200_BODY",
    retryPolicy: DEFAULT_RETRY,
    requiredFields: [
      "transactionKind",
      "transformKind",
      "submissionChannel",
      "memberId",
      "admissionDateTime",
      "primaryDiagnosisCode",
      "correlationId",
    ],
    effectiveDate: "2020-01-01T00:00:00.000Z",
    expirationDate: null,
    active: true,
    profile: {
      sourceType: "PUBLISHED_PAYER_REQUIREMENT_PROFILE",
      payerBrand: "Cigna",
      planProduct: "Commercial",
      transactionType: "ADMISSION_NOTIFICATION",
      notificationRequirement: "REQUIRED",
      authorizationRequirement: "NOT_REQUIRED_FOR_EMERGENCY_SERVICES",
      notificationWindow: {
        value: 1,
        unit: "BUSINESS_DAYS",
        startEvent: "EMERGENCY_ADMISSION_TIME",
      },
      submissionChannels: ["PROVIDER_SERVICES_PHONE"],
      acknowledgementBehavior:
        "MOCK_DELIVERY_ACK_ONLY — not an authorization approval; live ack behavior UNKNOWN",
      transformKind: "SYNTHETIC_DEMO_TRANSFORM",
      sourceReference: {
        requirementIds: [
          "CIGNA-COMM-EMERGENCY-IP-REPORT-001",
          "CIGNA-COMM-INPATIENT-NOTIFICATION-CHANNEL-001",
        ],
        source: "Cigna Precertifications page + Online Precert Guide 2025",
        sourceUrl:
          "https://www.cigna.com/health-care-providers/coverage-and-claims/precertification",
        verificationDate: "2026-09-10",
        evidence:
          "Report emergency→IP within one business day; inpatient notification not via online precert tool.",
      },
    },
  },
  {
    id: "44444444-4444-4444-8444-444444444008",
    contractBusinessId: "BCBSAZ_COMMERCIAL_INPATIENT_NOTIFICATION_V1",
    name: "BCBS Arizona Commercial inpatient admission notification profile",
    version: 1,
    payer: "COMMERCIAL",
    product: "NOA",
    payerBrand: "Blue Cross Blue Shield of Arizona",
    planProduct: "Commercial Group and Individual/Family",
    payloadFormat: "JSON",
    transport: "PORTAL_OR_FAX_OR_PHONE",
    destinationId: "22222222-2222-4222-8222-222222222001",
    transformerCode: "BCBSAZ_ADMISSION_NOTIFICATION_V1",
    acknowledgementType: "HTTP_200_BODY",
    retryPolicy: DEFAULT_RETRY,
    requiredFields: [
      "transactionKind",
      "transformKind",
      "memberId",
      "memberName",
      "dateOfBirth",
      "admissionDateTime",
      "diagnosisCodes",
      "facilityNpi",
      "correlationId",
    ],
    effectiveDate: "2020-01-01T00:00:00.000Z",
    expirationDate: null,
    active: true,
    profile: {
      sourceType: "PUBLISHED_PAYER_REQUIREMENT_PROFILE",
      payerBrand: "Blue Cross Blue Shield of Arizona",
      planProduct: "Commercial Group and Individual/Family",
      state: "AZ",
      transactionType: "ADMISSION_NOTIFICATION",
      notificationRequirement: "REQUIRED",
      authorizationRequirement: "CODE_DEPENDENT",
      notificationWindow: {
        value: 48,
        unit: "HOURS",
        startEvent: "ADMISSION_TIME",
      },
      submissionChannels: ["AVAILITY", "FAX", "PHONE"],
      acknowledgementBehavior:
        "MOCK_DELIVERY_ACK_ONLY — not an authorization approval",
      transformKind: "SYNTHETIC_DEMO_TRANSFORM",
      sourceReference: {
        requirementIds: [
          "BCBSAZ-COMM-POST-ADMISSION-NOTIFICATION-001",
          "BCBSAZ-COMM-REQUIRED-INFO-001",
        ],
        source: "AZ Blue Inpatient Admissions Quick Guide (Provider Operating Guide)",
        sourceUrl:
          "https://edge.sitecorecloud.io/bluecross-6f8ea2ea/media/project/bcbs-az/azblue/data/media/files/providers/resources/prior-auth-and-med-policies/inpatient-admissions-quick-guide.pdf",
        verificationDate: "2026-09-10",
        evidence:
          "Commercial post-admission notification within 48 hours; Availity/fax/phone channels documented.",
      },
    },
  },
];

/** Preferred default when multiple contracts match for the same payer. */
export const DEFAULT_NOA_CONTRACT_BUSINESS_ID = "MEDICARE_NOA_MOCK_V1";
